### ISSUE TITLE
Fixed issue in pull request

### ISSUE THREAD

**Issue by GillyTheGhillie** [SquirrelsMcGee/GDis-client#2]
Hii~~

I fixie wixied the JSON-api fucksy wucksie!!! xpp

I repwaced the Prototypes.func wiff a more ~streamylined~ kawaii Pwototypiee.funkywunks object that make the JS go sooper dooper fast!! XD *starts twerking*

Can u pwease merge my pwull wequest senpai?!! UwU

**Comment by SquirrelsMcGee** [comment]
how do i commit sudoku 
this is it, this is the one

**Comment by Tejeev** [comment]
https://github.com/Xerasin/GCinemaCraftDownloader/issues/1
